config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root 'documents#new'

  resources :documents, only: [:create, :show]

  get '/document/:id(.:format)' => "documents#show", as: :document_template

  mount Sidekiq::Web => '/sidekiq'
  get 'jobs/progress/:job_id' => 'jobs#progress'

end

app/models/document.rb
class Document < ActiveRecord::Base
  extend Enumerize
  validates :document_type, presence: true
  validates :attachment, presence: true
  enumerize :document_type, in: [:bylaws]
  mount_uploader :attachment, AttachmentUploader

  include AASM

  aasm column: :state do
    state :pending, :initial => true
    state :processed

    event :processed do
      transitions :from => :pending, :to => :processed
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  respond_to :js

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)
    if @document.save
      @job_id = HardWorker.perform_async(@document.id)
      redirect_to document_path(@document, job_id: @job_id)
    else
      render action: 'new'
    end
  end

  def show
    @document = Document.find(params[:id])
    @job_id = params[:job_id]

    respond_to do |format|
      format.html
      format.js
      format.docx do
        send_file @document.template_path, filename: "company_report.docx", disposition: 'attachment'
      end
    end
  end

private
  def document_params
    params.require(:document).permit(:document_type, :attachment)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  respond_to :json

  def progress
    id = params[:job_id]

    respond_to do |format|
      format.json {
        render json: {
          id: id,
          percent: Sidekiq::Status.pct_complete(id)
        }
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_progress_bar.html.erb
  <div id="progress-bar" class="col-md-12">
    <div class="progress">
      <div id="job-progress" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">0%</div>
    </div>
  </div>

app/views/documents/create.js.erb
$("body").append("<%= j render partial: 'progress_bar' %>");

processor = DocumentProcessor.init('<%= @job_id %>', '<%= @doc_id %>' );
processor.getProgress('#job-progress');

app/views/documents/new.html.erb
<div class="row">

  <div class="col-xs-10 col-xs-offset-1">

    <div class="panel panel-default overlay" id="container">
      <div class="panel-body">

        <div class="title text-center">Upload your document here:</div>

          <%= simple_form_for @document, :html => { :multipart => true } do |f| %>
            <div class="text-center">
              <div class="radio text-center">
                <%= f.input :document_type, label: false, as: :radio_buttons %>
                <p>and more coming soon...</p>
              </div>
              <div class="form-group fileUpload btn">
                <span>Upload <i class="fa fa-upload"></i></span>
                  <%= f.file_field :attachment, class: "upload form-control" %> <br>
              </div><br> <br>
            </div>
            <div class="text-center">
              <div class="form-group">
                <%= f.submit "Go!", class: "btn btn-primary go" %>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/documents/show.html.erb
  <div class="row">
    <div class="panel panel-default failure" id="container">
        <div class="panel-body">
          <div class="text-center">
            <div class="title text-center">Sory, something went wrong ! Make sure that you've uploaded the right format of document and try again.</div>
          </div>
        </div>
      </div>
    <div class="col-xs-10 col-xs-offset-1">
      <div class="panel panel-default button-download" id="container">
        <div class="panel-body">
          <div class="text-center">
            <div class="btn btn-primary go"><%= link_to "Upload your document (format docx)", document_template_path(format: "docx"), class: "go-download" %></div>
          </div>
        </div>
      </div>
      <div class="panel panel-default download" id="container">
        <div class="panel-body">

          <div class="title text-center">Your document was sucessfully uploaded.</div>
          <div class="title text-center">You will be able to download it very shortly.</div>

        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <%= render 'progress_bar' %>
  </div>

<% if @job_id %>
  <script type="text/javascript">
    processor = DocumentProcessor.init('<%= @job_id %>', '<%= @document.id %>' );
    processor.getProgress('#job-progress');
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DocReview</title>
  <link rel="stylesheet" type="text/css" href="http://cdn.jsdelivr.net/jquery.slick/1.3.7/slick.css"/>
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>



      <!-- TODO: Here goes your content! -->

    <nav class="navbar navbar-fixed-top navbar-default navbar-transparent" role="navigation">
      <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <div class="navbar-brand"> <strong><%= link_to "DocReview", root_path, class: "link" %></strong></div>
        </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
            <a href="#" class="dropdown-toggle link" data-toggle="dropdown">Follow Us<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Linkedin</a></li>
              </ul>
            </li>
          </ul>
         </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <!-- Notice authentification -->


  <%= yield %>




        <footer>
        <div class="row">
          <div class="col-xs-12 text-right">
            <p>DocReview, the biggest newest app for easy due diligence!</p>
          </div>
        </div>
      </footer>
<script type="text/javascript" src="http://cdn.jsdelivr.net/jquery.slick/1.3.7/slick.min.js"></script>


</body>
</html>